name: youtube_descriptions CI Workflow

# triggers for the workflow
on:
  push:
    branches:
      - master
      - cicd_workflow

env:
  DOCKER_REPO: "931976494498.dkr.ecr.eu-central-1.amazonaws.com/lambda-youtube-descriptions"

# job definitions
jobs:
  package-job: # package job for building and publishing docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code # checking out code.
        uses: actions/checkout@v2
      - name: Define varibles
        run: |
          cat version.txt >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.YOUTUBE_DESCRIPTIONS_VERSION }},
            ${{ env.DOCKER_REPO }}:latest
          push: true
      - name: Send notification
        uses: appleboy/telegram-action@master
        if: ${{ always() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            PACKAGE-JOB for *Cocktail Master v${{ env.YOUTUBE_DESCRIPTIONS_VERSION }}*
            in branch *${{ env.BRANCH }}* completed with a *${{ JOB.STATUS }}*
